// @ts-check
const WELCOME_SCREEN_ROUTE = 'Welcome'
const HOME_SCREEN_ROUTE = 'Home'
const MENU_SCREEN_ROUTE = 'Menu'
const SETTING_SCREEN_ROUTE = 'Setting'
const IMPRINT_SCREEN_ROUTE = 'Imprint'
const PRIVACY_SCREEN_ROUTE = 'Privacy'
const THIRD_PARTY_LIBS_SCREEN_ROUTE = 'ThirdPartyLibs'
const THIRD_PARTY_LIBS_DETAIL_SCREEN_ROUTE = 'ThirdPartyLibsDetail'
const ABOUT_SCREEN_ROUTE = 'About'
const MENU_MODAL_ROUTE = 'MenuModal'

export {
  WELCOME_SCREEN_ROUTE,
  HOME_SCREEN_ROUTE,
  MENU_SCREEN_ROUTE,
  SETTING_SCREEN_ROUTE,
  IMPRINT_SCREEN_ROUTE,
  PRIVACY_SCREEN_ROUTE,
  THIRD_PARTY_LIBS_SCREEN_ROUTE,
  THIRD_PARTY_LIBS_DETAIL_SCREEN_ROUTE,
  ABOUT_SCREEN_ROUTE,
  MENU_MODAL_ROUTE,
}
